version: "1.0"
info:
  model: int-scaffold
packages:
- name: SerengetiGH2509Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
- name: AddPublicService
  version: "6.0"
  gitServerName: srcCtrl_gitlab_Arti
  gitUrl: https://gitlab.com/ArtiKhareGitlab
  gitUsername: ArtiKhareGitlab
  gitBranch: master
- name: MultiplyPublicService
  version: "6.0"
  gitServerName: srcCtrl_shared_bitbucket_Arti
  gitUrl: https://bitbucket.org/testartiibm
  gitUsername: artik
  gitBranch: master
- name: OpenWeatherClient
  version: "1.0"
  wpmServer: https://packages.webmethods.io
  wpmRegistry: public
  wpmVersion: latest
- name: XMLBuiltInServices
  version: "1.0"
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
services:
- serviceName: project.serengetigh2509.integrations:bitbucketfs
  packages:
  - name: SerengetiGH2509Project
    version: "1.0"
  - name: AddPublicService
    version: "6.0"
  - name: XMLBuiltInServices
    version: "1.0"
  - name: MultiplyPublicService
    version: "6.0"
  - name: OpenWeatherClient
    version: "1.0"
- serviceName: MultiplyPublicService:multiply_svc
  packages:
  - name: MultiplyPublicService
    version: "6.0"
- serviceName: pub.math:multiplyInts
  packages:
  - name: WmPublic
    version: 12.1.0.0.1070
- serviceName: project.serengetigh2509.integrations:en
  packages:
  - name: SerengetiGH2509Project
    version: "1.0"
  - name: AddPublicService
    version: "6.0"
  - name: XMLBuiltInServices
    version: "1.0"
  - name: MultiplyPublicService
    version: "6.0"
  - name: OpenWeatherClient
    version: "1.0"
- serviceName: pub.security:encrypt
  packages:
  - name: WmPublic
    version: 12.1.0.0.1070
- serviceName: pub.security:decrypt
  packages:
  - name: WmPublic
    version: 12.1.0.0.1070
- serviceName: project.serengetigh2509.integrations:xl
  packages:
  - name: SerengetiGH2509Project
    version: "1.0"
  - name: AddPublicService
    version: "6.0"
  - name: XMLBuiltInServices
    version: "1.0"
  - name: MultiplyPublicService
    version: "6.0"
  - name: OpenWeatherClient
    version: "1.0"
- serviceName: XMLBuiltInServices:xmlFlexCascade
  packages:
  - name: XMLBuiltInServices
    version: "1.0"
- serviceName: pub.xml:xmlStringToXMLNode
  packages:
  - name: WmPublic
    version: 12.1.0.0.1070
- serviceName: pub.xml:getXMLNodeType
  packages:
  - name: WmPublic
    version: 12.1.0.0.1070
- serviceName: pub.xml:getXMLNodeIterator
  packages:
  - name: WmPublic
    version: 12.1.0.0.1070
- serviceName: pub.xml:getNextXMLNode
  packages:
  - name: WmPublic
    version: 12.1.0.0.1070
- serviceName: pub.xml:freeXMLNode
  packages:
  - name: WmPublic
    version: 12.1.0.0.1070
- serviceName: pub.xml:xmlStringToEnhancedXMLNode
  packages:
  - name: WmPublic
    version: 12.1.0.0.1070
- serviceName: pub.xml:queryXMLNode
  packages:
  - name: WmPublic
    version: 12.1.0.0.1070
- serviceName: pub.xml:xmlNodeToDocument
  packages:
  - name: WmPublic
    version: 12.1.0.0.1070
- serviceName: pub.xml:documentToXMLString
  packages:
  - name: WmPublic
    version: 12.1.0.0.1070
configurationVariables:
  jdbc.SAP TxStore Pool.maxConns: "10"
  jdbcfunc.SAPTxStore.failFastMode: false
  jdbc.SAP TxStore Pool.poolThreshold: "0"
  jdbc.SAP TxStore Pool.dbURL: jdbc:mysql://localhost:3306/SAPTRANSACTIONSTORE?useSSL=false&characterEncoding=utf-8&autoReconnect=true&maxReconnects=5&sessionVariables=wait_timeout=2147483
  jdbc.SAP TxStore Pool.spyenabled: "false"
  jdbc.SAP TxStore Pool.useSSL: "false"
  jdbc.SAP TxStore Pool.waitingThread: "10"
  jdbc.SAP TxStore Pool.description: Connection Pool for the SAP Transaction Store
  jdbc.SAP TxStore Pool.password: "{AES}nrGf3u7Wt20hFBGh5ZeEuQ=="
  jdbc.SAP TxStore Pool.spyparms: SpyAttributes=(log=(file)logs/spy/SAP_TxStore_Pool.log;logTName=yes;timestamp=yes)
  jdbc.SAP TxStore Pool.snoopenabled: "false"
  jdbc.SAP TxStore Pool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/SAP_TxStore_Pool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.SAP TxStore Pool.expireTime: "60000"
  jdbc.SAP TxStore Pool.minConns: "5"
  jdbc.SAP TxStore Pool.userid: root
  jdbc.SAP TxStore Pool.driverAlias: MySQL CC Driver
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
